"""Top-level save() and load() orchestration for the Torq storage layer.

Separated into _impl.py to avoid circular import risk: parquet.py, video.py,
and index.py may all be imported from storage/__init__.py, and splitting the
orchestration logic here ensures those modules never need to import each other.
"""

from __future__ import annotations

import logging
from pathlib import Path

from torq.episode import Episode
from torq.errors import TorqStorageError

__all__ = ["save", "load"]

logger = logging.getLogger(__name__)


def save(episode: Episode, path: str | Path, *, quiet: bool | None = None) -> Episode:
    """Persist an Episode to disk and return it with updated provenance fields.

    Directory layout created under ``path``:

    .. code-block:: text

        {path}/
        ├── episodes/
        │   └── ep_NNNN.parquet
        ├── videos/         (created only when image observations are present)
        │   └── ep_NNNN_{obs_key}.mp4
        └── index/
            ├── manifest.json
            ├── by_task.json
            ├── by_embodiment.json
            └── quality.json

    The Episode ID (``ep_{n:04d}`` format) is generated by
    ``storage/index.py`` and is the only place that generates IDs.

    Args:
        episode: The Episode to persist. Must have numeric arrays in ``observations``
            and ``actions``. ImageSequence observations are written as MP4 files.
        path: Root directory for the dataset. Created if it does not exist.
        quiet: Reserved for future use (suppress progress output). Currently unused.

    Returns:
        The same Episode object, mutated in-place: ``episode_id`` is updated to the
        generated ``ep_{n:04d}`` value and ``source_path`` is updated to the written
        Parquet path. The caller's reference to ``episode`` reflects these changes.

    Note:
        **In-place mutation**: ``episode_id`` and ``source_path`` are updated on the
        passed-in Episode via ``object.__setattr__`` (storage-layer bypass authorised
        by ``episode.py:80-84``). This is intentional — the caller gets back a
        fully-provenanced Episode without needing to capture the return value.

    Note:
        **R1 race condition**: ``_next_episode_id()`` reads the manifest counter and
        ``update_index()`` increments it in a separate step. Concurrent calls to
        ``save()`` in separate processes may generate the same ID. For R1 (single
        process, local I/O), this is not a concern; the duplicate-ID guard below
        raises immediately if the Parquet file already exists.

    Raises:
        TorqStorageError: On any file I/O failure, or if a Parquet file for the
            generated episode ID already exists (duplicate-ID guard).
    """
    from torq.storage.index import _next_episode_id, update_index
    from torq.storage.parquet import save_parquet
    from torq.storage.video import save_video

    root = Path(path)
    episodes_dir = root / "episodes"
    videos_dir = root / "videos"
    index_dir = root / "index"

    episodes_dir.mkdir(parents=True, exist_ok=True)
    index_dir.mkdir(parents=True, exist_ok=True)

    # 1. Generate Episode ID — index.py is the single source of truth
    episode_id = _next_episode_id(index_dir)

    # Duplicate-ID guard: reject immediately if a Parquet file already exists.
    # This catches R1 race conditions (two processes using the same dataset root)
    # before any data is written, preventing silent overwrite of existing episodes.
    candidate_parquet = episodes_dir / f"{episode_id}.parquet"
    if candidate_parquet.exists():
        raise TorqStorageError(
            f"Episode ID '{episode_id}' is already in use at '{candidate_parquet}'. "
            "The manifest counter may be out of sync with the episodes directory. "
            "Inspect the index/manifest.json and reconcile before saving."
        )

    object.__setattr__(episode, "episode_id", episode_id)

    # 2. Save non-image observations + actions + timestamps to Parquet
    try:
        parquet_path = save_parquet(episode, episodes_dir)
    except TorqStorageError:
        raise
    except Exception as exc:
        raise TorqStorageError(
            f"Failed to save episode '{episode_id}' to Parquet: {exc}. "
            f"Check write permissions on '{episodes_dir}'."
        ) from exc

    object.__setattr__(episode, "source_path", parquet_path)

    # 3. Save image observations to MP4 (conditional)
    # Duck-typing check: any obs with a .frames property is image data.
    # This supports both ImageSequence (from video files) and _InMemoryFrames
    # (from HDF5 ingestion) without coupling to concrete types.
    for obs_key, obs_val in episode.observations.items():
        if hasattr(obs_val, "frames"):
            videos_dir.mkdir(parents=True, exist_ok=True)
            save_video(obs_val, videos_dir / f"{episode_id}_{obs_key}.mp4")

    # 4. Update the sharded JSON index (atomic)
    try:
        update_index(episode_id, episode, index_dir)
    except Exception as exc:
        raise TorqStorageError(
            f"Failed to update index for episode '{episode_id}': {exc}. "
            f"Parquet file was written to '{parquet_path}' but the index is out of sync. "
            "Re-run save to retry index update."
        ) from exc

    logger.info("Saved Episode %s → %s", episode_id, root)
    return episode


def load(episode_id: str, path: str | Path) -> Episode:
    """Load an Episode from disk by its ID.

    Reads the Parquet file for numeric data, and wraps any corresponding MP4
    files as lazy ``ImageSequence`` observations.

    Args:
        episode_id: Episode ID to load (e.g. ``"ep_0001"``).
        path: Root dataset directory (same ``path`` passed to ``save()``).

    Returns:
        Fully populated Episode with all numeric fields and ImageSequence stubs.

    Raises:
        TorqStorageError: If the Parquet file is missing or cannot be read.
    """
    from torq.media.image_sequence import ImageSequence
    from torq.storage.parquet import load_parquet

    root = Path(path)

    # Load numeric data from Parquet
    episode = load_parquet(episode_id, root)

    # Attach any video files as ImageSequence observations.
    # Note: we mutate the `observations` dict of the freshly-constructed Episode.
    # This bypasses the `__setattr__` immutability guard (which only blocks
    # re-assignment of the `observations` *reference*), and is intentional —
    # load_parquet() constructs a fresh dict, so we are populating it, not
    # corrupting a caller-owned object.
    videos_dir = root / "videos"
    if videos_dir.exists():
        for mp4_path in sorted(videos_dir.glob(f"{episode_id}_*.mp4")):
            # Derive obs key from filename: ep_NNNN_{key}.mp4
            stem = mp4_path.stem  # e.g. "ep_0001_camera"
            prefix = f"{episode_id}_"
            if stem.startswith(prefix):
                obs_key = stem[len(prefix) :]
                episode.observations[obs_key] = ImageSequence(mp4_path)
                logger.debug("Loaded video observation '%s' from %s", obs_key, mp4_path)

    return episode
